services:
    GitWrapper\GitWrapper: null


# To add logging capabilities use monolog and this configuration:
#monolog:
#    channels:
#        - 'git'

#services:
#    GitWrapper\EventSubscriber\GitLoggerEventSubscriber:
#        $logger: '@monolog.logger.git'
#    GitWrapper\GitWrapper:
#        calls:
#            - addLoggerEventSubscriber: ['@GitWrapper\EventSubscriber\GitLoggerEventSubscriber']
