#index:
#    path: /
#    controller: App\Controller\DefaultController::index

_api:
  resource: routes/api.yml
  prefix: /api/v1

app_status:
  path: /phpinfo
  controller:  App\Controller\AppStatusController:phpinfoAction

#homepage:
#  path: /
#  defaults:  { _controller: App:Default:index }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# config/routes.yaml
app.redocly:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.redocly }
